# This notebook is an exploratory data analysis (EDA) process designed to clean up the dataset, calculate the weighted score for each stock's news, and merge them with stock price data.

In [2]:
# Read the parquet.

import pandas as pd

tesla_df = pd.read_parquet('./tesla_news.parquet')

tesla_df = tesla_df.drop_duplicates(subset=['title', 'time_published', 'url'])

tesla_df['date'] = pd.to_datetime(tesla_df['time_published']).dt.strftime('%Y%m%d')

tesla_df.date.unique()

array(['20220301', '20220302', '20220303', '20220304', '20220305',
       '20220306', '20220307', '20220308', '20220309', '20220310',
       '20220311', '20220312', '20220313', '20220314', '20220315',
       '20220316', '20220317', '20220318', '20220401', '20220402',
       '20220403', '20220404', '20220405', '20220406', '20220407',
       '20220501', '20220502', '20220503', '20220504', '20220505',
       '20220506', '20220507', '20220508', '20220509', '20220510',
       '20220601', '20220602', '20220603', '20220604', '20220605',
       '20220606', '20220607', '20220608', '20220609', '20220610',
       '20220701', '20220702', '20220703', '20220704', '20220705',
       '20220706', '20220707', '20220708', '20220709', '20220710',
       '20220711', '20220712', '20220713', '20220714', '20220801',
       '20220802', '20220803', '20220804', '20220805', '20220806',
       '20220807', '20220808', '20220809', '20220810', '20220811',
       '20220812', '20220813', '20220901', '20220902', '20220903',
       '20220904', '20220905', '20220906', '20220907', '20220908',
       '20220909', '20220910', '20220911', '20220912', '20220913',
       '20220914', '20220915', '20220916', '20221001', '20221002',
       '20221003', '20221004', '20221005', '20221006', '20221007',
       '20221008', '20221009', '20221010', '20221011', '20221101',
       '20221102', '20221103', '20221104', '20221105', '20221106',
       '20221107', '20221108', '20221109', '20221110', '20221111',
       '20221201', '20221202', '20221203', '20221204', '20221205',
       '20221206', '20221207', '20221208', '20221209', '20221210',
       '20221211', '20221212', '20221213', '20221214', '20221215',
       '20230101', '20230102', '20230103', '20230104', '20230105',
       '20230106', '20230107', '20230108', '20230109', '20230110',
       '20230111', '20230112', '20230201', '20230202', '20230203',
       '20230204', '20230205', '20230206', '20230207', '20230208',
       '20230209', '20230210', '20230211', '20230212', '20230213',
       '20230214', '20230301', '20230302', '20230303', '20230304',
       '20230305', '20230306', '20230307', '20230308', '20230309',
       '20230310', '20230311', '20230312', '20230313', '20230314',
       '20230401', '20230402', '20230403', '20230404', '20230405',
       '20230406', '20230407', '20230408', '20230409', '20230410',
       '20230411', '20230412', '20230413', '20230414', '20230501',
       '20230502', '20230503', '20230504', '20230505', '20230506',
       '20230507', '20230508', '20230509', '20230510', '20230511',
       '20230512', '20230513', '20230514', '20230515', '20230516',
       '20230601', '20230602', '20230603', '20230604', '20230605',
       '20230606', '20230607', '20230608', '20230609', '20230610',
       '20230611', '20230612', '20230613', '20230701', '20230702',
       '20230703', '20230704', '20230705', '20230706', '20230707',
       '20230708', '20230709', '20230710', '20230711', '20230712',
       '20230801', '20230802', '20230803', '20230804', '20230805',
       '20230806', '20230807', '20230808', '20230809', '20230810',
       '20230811', '20230812', '20230813', '20230814', '20230815',
       '20230816', '20230901', '20230902', '20230903', '20230904',
       '20230905', '20230906', '20230907', '20230908', '20231101',
       '20231102', '20231103', '20231104', '20231105', '20231106',
       '20231107', '20231108', '20231109', '20231110', '20231111',
       '20231112', '20231113', '20231114', '20231115', '20240101',
       '20240102', '20240103', '20240104', '20240105', '20240106',
       '20240107', '20240108', '20240109', '20240110', '20240111',
       '20240112', '20240113', '20240114', '20240301', '20240302',
       '20240303', '20240304', '20240305', '20240306', '20240307',
       '20240308', '20240309', '20240310', '20240311', '20240312',
       '20240313'], dtype=object)

In [3]:
# Read the parquet.
import pandas as pd

nvidia_df = pd.read_parquet('./nvidia_news.parquet')

nvidia_df = nvidia_df.drop_duplicates(subset=['title', 'time_published', 'url'])

nvidia_df['date'] = pd.to_datetime(nvidia_df['time_published']).dt.strftime('%Y%m%d')

nvidia_df.date.unique()

array(['20220303', '20220304', '20220306', '20220307', '20220308',
       '20220309', '20220310', '20220311', '20220312', '20220314',
       '20220315', '20220316', '20220317', '20220318', '20220319',
       '20220320', '20220321', '20220322', '20220323', '20220324',
       '20220325', '20220326', '20220327', '20220328', '20220329',
       '20220330', '20220331', '20220401', '20220402', '20220403',
       '20220404', '20220405', '20220406', '20220407', '20220408',
       '20220409', '20220410', '20220411', '20220412', '20220413',
       '20220414', '20220415', '20220416', '20220418', '20220419',
       '20220420', '20220421', '20220422', '20220423', '20220424',
       '20220425', '20220426', '20220427', '20220428', '20220429',
       '20220430', '20220502', '20220503', '20220504', '20220505',
       '20220506', '20220507', '20220508', '20220509', '20220510',
       '20220511', '20220512', '20220513', '20220514', '20220515',
       '20220516', '20220517', '20220518', '20220519', '20220520',
       '20220521', '20220522', '20220523', '20220524', '20220525',
       '20220526', '20220527', '20220528', '20220529', '20220530',
       '20220531', '20220601', '20220602', '20220603', '20220604',
       '20220605', '20220606', '20220607', '20220608', '20220609',
       '20220610', '20220611', '20220612', '20220613', '20220614',
       '20220615', '20220616', '20220617', '20220619', '20220620',
       '20220621', '20220622', '20220623', '20220624', '20220625',
       '20220626', '20220627', '20220628', '20220629', '20220630',
       '20220701', '20220702', '20220703', '20220704', '20220705',
       '20220706', '20220707', '20220708', '20220709', '20220710',
       '20220711', '20220712', '20220713', '20220714', '20220715',
       '20220716', '20220718', '20220719', '20220720', '20220721',
       '20220722', '20220723', '20220724', '20220725', '20220726',
       '20220727', '20220728', '20220729', '20220730', '20220731',
       '20220801', '20220802', '20220803', '20220804', '20220805',
       '20220806', '20220807', '20220808', '20220809', '20220810',
       '20220811', '20220812', '20220813', '20220814', '20220815',
       '20220816', '20220817', '20220818', '20220819', '20220820',
       '20220821', '20220822', '20220823', '20220824', '20220825',
       '20220826', '20220827', '20220828', '20220829', '20220830',
       '20220831', '20220901', '20220902', '20220903', '20220904',
       '20220905', '20220906', '20220907', '20220908', '20220909',
       '20220910', '20220911', '20220912', '20220913', '20220914',
       '20220915', '20220916', '20220917', '20220918', '20220919',
       '20220920', '20220921', '20220922', '20220923', '20220924',
       '20220925', '20220926', '20220927', '20220928', '20220929',
       '20220930', '20221001', '20221002', '20221003', '20221004',
       '20221005', '20221006', '20221007', '20221008', '20221009',
       '20221010', '20221011', '20221012', '20221013', '20221014',
       '20221015', '20221016', '20221017', '20221018', '20221019',
       '20221020', '20221021', '20221022', '20221023', '20221024',
       '20221025', '20221026', '20221027', '20221028', '20221029',
       '20221030', '20221031', '20221101', '20221102', '20221103',
       '20221104', '20221105', '20221106', '20221107', '20221108',
       '20221109', '20221110', '20221111', '20221112', '20221113',
       '20221114', '20221115', '20221116', '20221117', '20221118',
       '20221119', '20221120', '20221121', '20221122', '20221123',
       '20221124', '20221125', '20221126', '20221127', '20221128',
       '20221129', '20221130', '20221201', '20221202', '20221203',
       '20221204', '20221205', '20221206', '20221207', '20221208',
       '20221209', '20221210', '20221211', '20221212', '20221213',
       '20221214', '20221215', '20221216', '20221217', '20221218',
       '20221219', '20221220', '20221221', '20221222', '20221223',
       '20221224', '20221225', '20221226', '20221227', '20221228',
       '20221229', '20221230', '20221231', '20230101', '20230102',
       '20230103', '20230104', '20230105', '20230106', '20230107',
       '20230108', '20230109', '20230110', '20230111', '20230112',
       '20230113', '20230114', '20230115', '20230116', '20230117',
       '20230118', '20230119', '20230120', '20230121', '20230122',
       '20230123', '20230124', '20230125', '20230126', '20230127',
       '20230128', '20230129', '20230130', '20230131', '20230201',
       '20230202', '20230203', '20230204', '20230205', '20230206',
       '20230207', '20230208', '20230209', '20230210', '20230211',
       '20230212', '20230213', '20230214', '20230215', '20230216',
       '20230217', '20230218', '20230219', '20230220', '20230221',
       '20230222', '20230223', '20230224', '20230225', '20230226',
       '20230227', '20230228', '20230301', '20230302', '20230303',
       '20230304', '20230305', '20230306', '20230307', '20230308',
       '20230309', '20230310', '20230311', '20230312', '20230313',
       '20230314', '20230315', '20230316', '20230317', '20230318',
       '20230319', '20230320', '20230321', '20230322', '20230323',
       '20230324', '20230325', '20230326', '20230327', '20230328',
       '20230329', '20230330', '20230331', '20230401', '20230402',
       '20230403', '20230404', '20230405', '20230406', '20230407',
       '20230408', '20230409', '20230410', '20230411', '20230412',
       '20230413', '20230414', '20230415', '20230416', '20230417',
       '20230418', '20230419', '20230420', '20230421', '20230422',
       '20230423', '20230424', '20230425', '20230426', '20230427',
       '20230428', '20230429', '20230430', '20230501', '20230502',
       '20230503', '20230504', '20230505', '20230506', '20230507',
       '20230508', '20230509', '20230510', '20230511', '20230512',
       '20230513', '20230514', '20230515', '20230516', '20230517',
       '20230518', '20230519', '20230520', '20230521', '20230522',
       '20230601', '20230602', '20230603', '20230604', '20230605',
       '20230606', '20230607', '20230608', '20230609', '20230610',
       '20230611', '20230612', '20230613', '20230614', '20230615',
       '20230616', '20230701', '20230702', '20230703', '20230704',
       '20230705', '20230706', '20230707', '20230708', '20230709',
       '20230710', '20230711', '20230712', '20230713', '20230714',
       '20230715', '20230716', '20230717', '20230718', '20230719',
       '20230801', '20230802', '20230803', '20230804', '20230805',
       '20230806', '20230807', '20230808', '20230809', '20230810',
       '20230811', '20230812', '20230813', '20230814', '20230815',
       '20230816', '20230817', '20230818', '20230901', '20230902',
       '20230903', '20230904', '20230905', '20230906', '20230907',
       '20230908', '20230909', '20230910', '20230911', '20230912',
       '20230913', '20230914', '20230915', '20230916', '20230917',
       '20230918', '20231101', '20231102', '20231103', '20231104',
       '20231105', '20231106', '20231107', '20231108', '20231109',
       '20231110', '20231111', '20231112', '20231113', '20231114',
       '20231115', '20231116', '20231117', '20231118', '20231119',
       '20231120', '20240101', '20240102', '20240103', '20240104',
       '20240105', '20240106', '20240107', '20240108', '20240109',
       '20240110', '20240111', '20240112', '20240113', '20240114',
       '20240115', '20240116', '20240117', '20240301', '20240302',
       '20240303', '20240304', '20240305', '20240306', '20240307',
       '20240308', '20240309', '20240310', '20240311'], dtype=object)

In [4]:
import pandas as pd

apple_df = pd.read_parquet('./apple_news.parquet')

apple_df = apple_df.drop_duplicates(subset=['title', 'time_published', 'url'])

apple_df['date'] = pd.to_datetime(apple_df['time_published']).dt.strftime('%Y%m%d')

apple_df['date'].unique()

array(['20220301', '20220302', '20220303', '20220304', '20220305',
       '20220306', '20220307', '20220308', '20220309', '20220310',
       '20220311', '20220312', '20220313', '20220314', '20220315',
       '20220316', '20220317', '20220318', '20220319', '20220320',
       '20220321', '20220322', '20220323', '20220324', '20220325',
       '20220401', '20220402', '20220403', '20220404', '20220405',
       '20220406', '20220407', '20220408', '20220409', '20220410',
       '20220411', '20220412', '20220413', '20220414', '20220415',
       '20220416', '20220417', '20220418', '20220419', '20220420',
       '20220421', '20220422', '20220423', '20220424', '20220425',
       '20220501', '20220502', '20220503', '20220504', '20220505',
       '20220506', '20220507', '20220508', '20220509', '20220510',
       '20220511', '20220512', '20220513', '20220514', '20220515',
       '20220516', '20220517', '20220518', '20220519', '20220520',
       '20220521', '20220522', '20220523', '20220601', '20220602',
       '20220603', '20220604', '20220605', '20220606', '20220607',
       '20220608', '20220609', '20220610', '20220611', '20220612',
       '20220613', '20220614', '20220615', '20220616', '20220617',
       '20220618', '20220619', '20220620', '20220621', '20220622',
       '20220623', '20220624', '20220625', '20220626', '20220627',
       '20220701', '20220702', '20220703', '20220704', '20220705',
       '20220706', '20220707', '20220708', '20220709', '20220710',
       '20220711', '20220712', '20220713', '20220714', '20220715',
       '20220716', '20220717', '20220718', '20220719', '20220720',
       '20220721', '20220722', '20220723', '20220724', '20220725',
       '20220726', '20220727', '20220801', '20220802', '20220803',
       '20220804', '20220805', '20220806', '20220807', '20220808',
       '20220809', '20220810', '20220811', '20220812', '20220813',
       '20220814', '20220815', '20220816', '20220817', '20220818',
       '20220819', '20220820', '20220821', '20220822', '20220823',
       '20220824', '20220825', '20220826', '20220901', '20220902',
       '20220903', '20220904', '20220905', '20220906', '20220907',
       '20220908', '20220909', '20220910', '20220911', '20220912',
       '20220913', '20220914', '20220915', '20220916', '20220917',
       '20220918', '20220919', '20220920', '20220921', '20220922',
       '20220923', '20220924', '20220925', '20220926', '20221001',
       '20221002', '20221003', '20221004', '20221005', '20221006',
       '20221007', '20221008', '20221009', '20221010', '20221011',
       '20221012', '20221013', '20221014', '20221015', '20221016',
       '20221017', '20221018', '20221019', '20221020', '20221021',
       '20221022', '20221023', '20221024', '20221101', '20221102',
       '20221103', '20221104', '20221105', '20221106', '20221107',
       '20221108', '20221109', '20221110', '20221111', '20221112',
       '20221113', '20221114', '20221115', '20221116', '20221117',
       '20221118', '20221119', '20221120', '20221121', '20221122',
       '20221123', '20221124', '20221125', '20221201', '20221202',
       '20221203', '20221204', '20221205', '20221206', '20221207',
       '20221208', '20221209', '20221210', '20221211', '20221212',
       '20221213', '20221214', '20221215', '20221216', '20221217',
       '20221218', '20221219', '20221220', '20221221', '20221222',
       '20221223', '20221224', '20221225', '20221226', '20221227',
       '20221228', '20230101', '20230102', '20230103', '20230104',
       '20230105', '20230106', '20230107', '20230108', '20230109',
       '20230110', '20230111', '20230112', '20230113', '20230114',
       '20230115', '20230116', '20230117', '20230118', '20230119',
       '20230120', '20230121', '20230122', '20230123', '20230124',
       '20230125', '20230126', '20230201', '20230202', '20230203',
       '20230204', '20230205', '20230206', '20230207', '20230208',
       '20230209', '20230210', '20230211', '20230212', '20230213',
       '20230214', '20230215', '20230216', '20230217', '20230218',
       '20230219', '20230220', '20230221', '20230222', '20230223',
       '20230224', '20230225', '20230226', '20230227', '20230228',
       '20230301', '20230302', '20230303', '20230304', '20230305',
       '20230306', '20230307', '20230308', '20230309', '20230310',
       '20230311', '20230312', '20230313', '20230314', '20230315',
       '20230316', '20230317', '20230318', '20230319', '20230320',
       '20230321', '20230322', '20230323', '20230324', '20230325',
       '20230326', '20230327', '20230328', '20230329', '20230330',
       '20230331', '20230401', '20230402', '20230403', '20230404',
       '20230405', '20230406', '20230407', '20230408', '20230409',
       '20230410', '20230411', '20230412', '20230413', '20230414',
       '20230415', '20230416', '20230417', '20230418', '20230419',
       '20230420', '20230421', '20230422', '20230423', '20230424',
       '20230425', '20230426', '20230427', '20230428', '20230429',
       '20230430', '20230501', '20230502', '20230503', '20230504',
       '20230505', '20230506', '20230507', '20230508', '20230509',
       '20230510', '20230511', '20230512', '20230513', '20230514',
       '20230515', '20230516', '20230517', '20230518', '20230519',
       '20230520', '20230521', '20230522', '20230523', '20230524',
       '20230525', '20230601', '20230602', '20230603', '20230604',
       '20230605', '20230606', '20230607', '20230608', '20230609',
       '20230610', '20230611', '20230612', '20230613', '20230614',
       '20230615', '20230616', '20230617', '20230618', '20230619',
       '20230620', '20230621', '20230622', '20230623', '20230624',
       '20230625', '20230626', '20230627', '20230701', '20230702',
       '20230703', '20230704', '20230705', '20230706', '20230707',
       '20230708', '20230709', '20230710', '20230711', '20230712',
       '20230713', '20230714', '20230715', '20230716', '20230717',
       '20230718', '20230719', '20230720', '20230721', '20230722',
       '20230723', '20230724', '20230725', '20230726', '20230727',
       '20230728', '20230801', '20230802', '20230803', '20230804',
       '20230805', '20230806', '20230807', '20230808', '20230809',
       '20230810', '20230811', '20230812', '20230813', '20230814',
       '20230815', '20230816', '20230817', '20230818', '20230819',
       '20230820', '20230821', '20230822', '20230823', '20230824',
       '20230901', '20230902', '20230903', '20230904', '20230905',
       '20230906', '20230907', '20230908', '20230909', '20230910',
       '20230911', '20230912', '20230913', '20230914', '20230915',
       '20230916', '20230917', '20230918', '20230919', '20230920',
       '20230921', '20231101', '20231102', '20231103', '20231104',
       '20231105', '20231106', '20231107', '20231108', '20231109',
       '20231110', '20231111', '20231112', '20231113', '20231114',
       '20231115', '20231116', '20231117', '20231118', '20231119',
       '20231120', '20231121', '20231122', '20231123', '20231124',
       '20231125', '20231126', '20231127', '20231128', '20231129',
       '20240101', '20240102', '20240103', '20240104', '20240105',
       '20240106', '20240107', '20240108', '20240109', '20240110',
       '20240111', '20240112', '20240113', '20240114', '20240115',
       '20240116', '20240117', '20240118', '20240119', '20240120',
       '20240121', '20240122', '20240123', '20240124', '20240125',
       '20240126', '20240301', '20240302', '20240303', '20240304',
       '20240305', '20240306', '20240307', '20240308', '20240309',
       '20240310', '20240311', '20240312', '20240313', '20240314',
       '20240315', '20240316', '20240317', '20240318', '20240319',
       '20240320', '20240321', '20240322', '20240323', '20240324',
       '20240325', '20240326', '20240327'], dtype=object)

In [5]:
priority_score = {
    'The Week News': 1,
    'Wall Street Journal': 4,
    'GlobeNewswire': 1,
    'Zacks Commentary': 1,
    'Reuters': 4,
    'CNBC': 1,
    'The Atlantic': 1,
    'New York Times': 4.5,
    'Decrypt.co': 1,
    'Investing News Network': 1,
    'Investors Business Daily': 1,
    'The Block Crypto': 1,
    'StockMarket.com': 1,
    'Forbes': 3.5,
    'Fox Business News': 1,
    'The Financial Express': 1,
    'Motley Fool': 1,
    'Cointelegraph': 1,
    'PennyStocks.com': 1,
    'The Street': 1,
    'Economic Times': 1,
    'Money Control': 1,
    'Al Jareeza': 1,
    'Benzinga': 1,
    'Axios': 1,
    'MarketWatch': 1,
    'CNN': 4,
    'Stocknews.com': 1,
    'The Economist': 4,
    'Money Morning': 1,
    'Kiplinger': 1,
    'Associated Press': 4.5,
    'Barrons': 1,
    'Financial News London': 1,
    'FinancialBuzz': 1,
    'Fast Company': 1,
    'Financial Times': 4,
    'Business Standard': 1,
    'UPI Business': 1,
    'South China Morning Post': 3.5,
    'Business Insider': 1,
    'Investor Ideas': 1,
    'Canada Newswire': 1,
    'PR Newswire': 1
}

apple_df_cp = apple_df.copy()

apple_df_cp['priority'] = apple_df_cp['source'].map(priority_score)

apple_df_cp['weighted_score'] = apple_df_cp.overall_sentiment_score * apple_df_cp.priority
apple_df_cp.head()

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment,date,priority,weighted_score
0,"US stocks fall, oil tops $105 as Ukraine crisi...",https://www.aljazeera.com/economy/2022/3/1/us-...,20220301T080000,[Rita Nazareth],A surge in oil sent shivers through risky asse...,https://www.aljazeera.com/wp-content/uploads/2...,Al Jareeza,n/a,www.aljazeera.com,"[{'relevance_score': '0.928139', 'topic': 'Eco...",-0.277460,Somewhat-Bearish,"[{'relevance_score': '0.062711', 'ticker': 'AA...",20220301,1.0,-0.277460
1,Apple halts product sales in Russia after Ukra...,https://www.scmp.com/tech/big-tech/article/316...,20220302T020013,[Bloomberg],Apple Inc halted sales of the iPhone and its o...,https://img.i-scmp.com/cdn-cgi/image/fit=conta...,South China Morning Post,Companies,www.scmp.com,"[{'relevance_score': '0.5', 'topic': 'Technolo...",-0.495467,Bearish,"[{'relevance_score': '0.078175', 'ticker': 'HP...",20220302,3.5,-1.734134
2,Russia says its economy is taking 'serious blo...,https://www.cnn.com/2022/03/02/business/russia...,20220302T080000,"[Mark Thompson and Vasco Cotovio, CNN Business]",London/Moscow ( CNN Business ) The Russian...,https://cdn.cnn.com/cnnnext/dam/assets/2203011...,CNN,Markets,www.cnn.com,"[{'relevance_score': '0.682689', 'topic': 'Eco...",-0.469431,Bearish,"[{'relevance_score': '0.078766', 'ticker': 'EA...",20220302,4.0,-1.877724
3,"Rich Russians turn to luxury jewellery, watche...",https://www.aljazeera.com/economy/2022/3/2/ric...,20220302T080000,"[Angelina Rascouet and Andy Hoffman, Flavia Ro...",With sanctions on Russia sending the ruble plu...,https://www.aljazeera.com/wp-content/uploads/2...,Al Jareeza,n/a,www.aljazeera.com,"[{'relevance_score': '0.158519', 'topic': 'Eco...",-0.118323,Neutral,"[{'relevance_score': '0.051474', 'ticker': 'AA...",20220302,1.0,-0.118323
4,"Market Rallies, But Still Must Do This; 5 Stoc...",https://www.investors.com/market-trend/stock-m...,20220303T080000,"[Investor's Business Daily, ED CARSON]",Dow Jones Futures: Stock Market Rallies On 'Ni...,https://www.investors.com/wp-content/uploads/2...,Investors Business Daily,n/a,www.investors.com,"[{'relevance_score': '0.25', 'topic': 'Life Sc...",-0.092622,Neutral,"[{'relevance_score': '0.149718', 'ticker': 'AA...",20220303,1.0,-0.092622

In [6]:
priority_score = {
    'The Week News': 1,
    'Wall Street Journal': 4,
    'GlobeNewswire': 1,
    'Zacks Commentary': 1,
    'Reuters': 4,
    'CNBC': 1,
    'The Atlantic': 1,
    'New York Times': 4.5,
    'Decrypt.co': 1,
    'Investing News Network': 1,
    'Investors Business Daily': 1,
    'The Block Crypto': 1,
    'StockMarket.com': 1,
    'Forbes': 3.5,
    'Fox Business News': 1,
    'The Financial Express': 1,
    'Motley Fool': 1,
    'Cointelegraph': 1,
    'PennyStocks.com': 1,
    'The Street': 1,
    'Economic Times': 1,
    'Money Control': 1,
    'Al Jareeza': 1,
    'Benzinga': 1,
    'Axios': 1,
    'MarketWatch': 1,
    'CNN': 4,
    'Stocknews.com': 1,
    'The Economist': 4,
    'Money Morning': 1,
    'Kiplinger': 1,
    'Associated Press': 4.5,
    'Barrons': 1,
    'Financial News London': 1,
    'FinancialBuzz': 1,
    'Fast Company': 1,
    'Financial Times': 4,
    'Business Standard': 1,
    'UPI Business': 1,
    'South China Morning Post': 3.5,
    'Business Insider': 1,
    'Investor Ideas': 1,
    'Canada Newswire': 1,
    'PR Newswire': 1
}

nvidia_df_cp = nvidia_df.copy()

nvidia_df_cp['priority'] = nvidia_df_cp['source'].map(priority_score)

nvidia_df_cp['weighted_score'] = nvidia_df_cp.overall_sentiment_score * nvidia_df_cp.priority
nvidia_df_cp.head()

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment,date,priority,weighted_score
0,MarketingPulse and eTailingPulse to shed light...,https://www.scmp.com/presented/business/topics...,20220303T065619,[Advertising partner],[Sponsored Article]\r\rThe Covid-19 pandemic h...,https://cdn.i-scmp.com/sites/default/files/sty...,South China Morning Post,Business,www.scmp.com,"[{'relevance_score': '0.5', 'topic': 'Technolo...",0.010325,Neutral,"[{'relevance_score': '0.045456', 'ticker': 'MS...",20220303,3.5,0.036138
1,20 Stocks Billionaires Are Selling,https://www.kiplinger.com/investing/stocks/604...,20220303T210336,[Will Ashworth],A lot of money continues to flow into hedge fu...,https://mediacloud.kiplinger.com/image/private...,Kiplinger,n/a,www.kiplinger.com,"[{'relevance_score': '0.142857', 'topic': 'Lif...",-0.009081,Neutral,"[{'relevance_score': '0.043034', 'ticker': 'CE...",20220303,1.0,-0.009081
2,The Top 5 Investment Plays for Blockchain,https://www.zacks.com/stock/news/1877770/the-t...,20220304T172200,[Zacks Investment Research],There are plenty of ways to invest in blockcha...,https://staticx-tuner.zacks.com/images/article...,Zacks Commentary,n/a,www.zacks.com,"[{'relevance_score': '0.158519', 'topic': 'Eco...",0.125201,Neutral,"[{'relevance_score': '0.02519', 'ticker': 'NVD...",20220304,1.0,0.125201
3,Nvidia Faces an Unusual Demand That Threatens ...,https://www.thestreet.com/investing/nvidia-fac...,20220304T193600,[Riley Gutiérrez McDermid],The chip giant was recently the victim of a hack.,https://www.thestreet.com/.image/t_share/MTg1O...,The Street,n/a,www.thestreet.com,"[{'relevance_score': '0.158519', 'topic': 'Blo...",-0.311832,Somewhat-Bearish,"[{'relevance_score': '0.609839', 'ticker': 'NV...",20220304,1.0,-0.311832
4,"Amid Russia's war, America Inc reckons with th...",https://www.economist.com/business/2022/03/06/...,20220306T000000,[],Multinational companies grapple with a fractur...,https://www.economist.com/img/b/608/662/90/sit...,The Economist,Business,www.economist.com,"[{'relevance_score': '0.2', 'topic': 'Energy &...",-0.365286,Bearish,"[{'relevance_score': '0.022664', 'ticker': 'EA...",20220306,4.0,-1.461144

In [7]:
priority_score = {
    'The Week News': 1,
    'Wall Street Journal': 4,
    'GlobeNewswire': 1,
    'Zacks Commentary': 1,
    'Reuters': 4,
    'CNBC': 1,
    'The Atlantic': 1,
    'New York Times': 4.5,
    'Decrypt.co': 1,
    'Investing News Network': 1,
    'Investors Business Daily': 1,
    'The Block Crypto': 1,
    'StockMarket.com': 1,
    'Forbes': 3.5,
    'Fox Business News': 1,
    'The Financial Express': 1,
    'Motley Fool': 1,
    'Cointelegraph': 1,
    'PennyStocks.com': 1,
    'The Street': 1,
    'Economic Times': 1,
    'Money Control': 1,
    'Al Jareeza': 1,
    'Benzinga': 1,
    'Axios': 1,
    'MarketWatch': 1,
    'CNN': 4,
    'Stocknews.com': 1,
    'The Economist': 4,
    'Money Morning': 1,
    'Kiplinger': 1,
    'Associated Press': 4.5,
    'Barrons': 1,
    'Financial News London': 1,
    'FinancialBuzz': 1,
    'Fast Company': 1,
    'Financial Times': 4,
    'Business Standard': 1,
    'UPI Business': 1,
    'South China Morning Post': 3.5,
    'Business Insider': 1,
    'Investor Ideas': 1,
    'Canada Newswire': 1,
    'PR Newswire': 1
}

tesla_df_cp = tesla_df.copy()

tesla_df_cp['priority'] = tesla_df_cp['source'].map(priority_score)

tesla_df_cp['weighted_score'] = tesla_df_cp.overall_sentiment_score * tesla_df_cp.priority
tesla_df_cp.head()

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment,date,priority,weighted_score
0,Tesla Rival Slashes 2022 Production Outlook; L...,https://www.investors.com/news/lucid-stock-luc...,20220301T080000,"[APARNA NARAYANAN, Investor's Business Daily]",Lucid Stock Sinks As Tesla Rival Slashes 2022 ...,https://www.investors.com/wp-content/uploads/2...,Investors Business Daily,n/a,www.investors.com,"[{'relevance_score': '0.996023', 'topic': 'Fin...",-0.196652,Somewhat-Bearish,"[{'relevance_score': '0.782347', 'ticker': 'LC...",20220301,1.0,-0.196652
1,Nasdaq moves into positive territory as broade...,https://www.cnn.com/business/live-news/stock-m...,20220301T080000,[By CNN Business],Live updates: Dow tumbles as Russia threatens ...,https://dynaimage.cdn.cnn.com/cnn/digital-imag...,CNN,Markets,www.cnn.com,"[{'relevance_score': '0.576289', 'topic': 'Eco...",-0.337465,Somewhat-Bearish,"[{'relevance_score': '0.060833', 'ticker': 'NF...",20220301,4.0,-1.349860
2,BYD to use Baidu's autonomous driving technolo...,https://www.scmp.com/business/china-business/a...,20220301T113014,[Daniel Ren],"BYD, China's biggest electric vehicle (EV) bui...",https://img.i-scmp.com/cdn-cgi/image/fit=conta...,South China Morning Post,Companies,www.scmp.com,"[{'relevance_score': '0.333333', 'topic': 'Tec...",0.092964,Neutral,"[{'relevance_score': '0.072043', 'ticker': 'XP...",20220301,3.5,0.325374
3,Chinese electric car makers' February sales de...,https://www.scmp.com/business/china-business/a...,20220301T163019,[Daniel Ren],China's three biggest makers of smart electric...,https://img.i-scmp.com/cdn-cgi/image/fit=conta...,South China Morning Post,Companies,www.scmp.com,"[{'relevance_score': '0.360215', 'topic': 'Fin...",-0.077390,Neutral,"[{'relevance_score': '0.076798', 'ticker': 'BA...",20220301,3.5,-0.270865
4,"Box Stock Jumps As Fourth-Quarter Results, Out...",https://www.investors.com/news/technology/box-...,20220302T080000,"[Investor's Business Daily, BRIAN DEAGON]",Box Stock Jumps As Earnings Beat Estimates Inv...,https://www.investors.com/wp-content/uploads/2...,Investors Business Daily,n/a,www.investors.com,"[{'relevance_score': '0.158519', 'topic': 'IPO...",0.118697,Neutral,"[{'relevance_score': '0.166513', 'ticker': 'TS...",20220302,1.0,0.118697

In [8]:
# Calculate daily weighted average
daily_weighted_avg_tsla = tesla_df_cp.groupby('date').apply(
    lambda x: x['weighted_score'].sum() / x['priority'].sum()
).reset_index(name='daily_weighted_avg')

# # Merge the calculated daily weighted averages back into the original DataFrame on 'date'
# tesla_df_cp = pd.merge(tesla_df_cp, daily_weighted_avg_tsla, on='date', how='left')

daily_weighted_avg_tsla['company_name'] = 'Tesla Inc'

daily_weighted_avg_tsla

/var/folders/f9/s_p2lp2s61v9bz87s04_kj540000gn/T/ipykernel_7314/3949041377.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_weighted_avg_tsla = tesla_df_cp.groupby('date').apply(

         date  daily_weighted_avg company_name
0    20220301           -0.124334    Tesla Inc
1    20220302           -0.041356    Tesla Inc
2    20220303           -0.085926    Tesla Inc
3    20220304            0.021971    Tesla Inc
4    20220305           -0.251406    Tesla Inc
..        ...                 ...          ...
281  20240309            0.089587    Tesla Inc
282  20240310            0.064080    Tesla Inc
283  20240311            0.132596    Tesla Inc
284  20240312            0.053200    Tesla Inc
285  20240313            0.042799    Tesla Inc

[286 rows x 3 columns]

In [9]:
# Calculate daily weighted average
daily_weighted_avg_nvid = nvidia_df_cp.groupby('date').apply(
    lambda x: x['weighted_score'].sum() / x['priority'].sum()
).reset_index(name='daily_weighted_avg')

# # Merge the calculated daily weighted averages back into the original DataFrame on 'date'
# nvidia_df_cp = pd.merge(nvidia_df_cp, daily_weighted_avg_nvid, on='date', how='left')
daily_weighted_avg_nvid['company_name'] = 'NVIDIA Corp'

daily_weighted_avg_nvid

/var/folders/f9/s_p2lp2s61v9bz87s04_kj540000gn/T/ipykernel_7314/1122848490.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_weighted_avg_nvid = nvidia_df_cp.groupby('date').apply(

         date  daily_weighted_avg company_name
0    20220303            0.006013  NVIDIA Corp
1    20220304           -0.093315  NVIDIA Corp
2    20220306           -0.365286  NVIDIA Corp
3    20220307           -0.080469  NVIDIA Corp
4    20220308            0.023030  NVIDIA Corp
..        ...                 ...          ...
554  20240307            0.196732  NVIDIA Corp
555  20240308            0.169972  NVIDIA Corp
556  20240309            0.194364  NVIDIA Corp
557  20240310            0.187043  NVIDIA Corp
558  20240311            0.167731  NVIDIA Corp

[559 rows x 3 columns]

In [10]:
# Calculate daily weighted average
daily_weighted_avg_appl = apple_df_cp.groupby('date').apply(
    lambda x: x['weighted_score'].sum() / x['priority'].sum()
).reset_index(name='daily_weighted_avg')

# # Merge the calculated daily weighted averages back into the original DataFrame on 'date'
# apple_df_cp = pd.merge(apple_df_cp, daily_weighted_avg_appl, on='date', how='left')

daily_weighted_avg_appl['company_name'] = 'APPLE Inc'

daily_weighted_avg_appl

/var/folders/f9/s_p2lp2s61v9bz87s04_kj540000gn/T/ipykernel_7314/40101666.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_weighted_avg_appl = apple_df_cp.groupby('date').apply(

         date  daily_weighted_avg company_name
0    20220301           -0.277460    APPLE Inc
1    20220302           -0.438845    APPLE Inc
2    20220303           -0.204386    APPLE Inc
3    20220304            0.041050    APPLE Inc
4    20220305           -0.038863    APPLE Inc
..        ...                 ...          ...
573  20240323            0.158633    APPLE Inc
574  20240324            0.193345    APPLE Inc
575  20240325            0.123114    APPLE Inc
576  20240326            0.187346    APPLE Inc
577  20240327            0.149851    APPLE Inc

[578 rows x 3 columns]

In [11]:
# Combine the DataFrames
combined_df = pd.concat([daily_weighted_avg_appl, daily_weighted_avg_nvid, daily_weighted_avg_tsla], ignore_index=True)

combined_df['Date'] = pd.to_datetime(combined_df['date'], format='%Y%m%d')

# Drop the original date column if it's no longer needed
combined_df.drop('date', axis=1, inplace=True)

combined_df

      daily_weighted_avg company_name       Date
0              -0.277460    APPLE Inc 2022-03-01
1              -0.438845    APPLE Inc 2022-03-02
2              -0.204386    APPLE Inc 2022-03-03
3               0.041050    APPLE Inc 2022-03-04
4              -0.038863    APPLE Inc 2022-03-05
...                  ...          ...        ...
1418            0.089587    Tesla Inc 2024-03-09
1419            0.064080    Tesla Inc 2024-03-10
1420            0.132596    Tesla Inc 2024-03-11
1421            0.053200    Tesla Inc 2024-03-12
1422            0.042799    Tesla Inc 2024-03-13

[1423 rows x 3 columns]

In [13]:
import pandas as pd

df_stock = pd.read_csv('./stock_data.csv')

df_stock['Date'] = pd.to_datetime(combined_df['Date'], format='%Y%m%d')

df_stock

,Date,Open,High,Low,Close,Adj Close,Volume,company_name
0,2022-03-01,164.699997,166.600006,161.970001,163.199997,161.356049,83474400,APPLE Inc
1,2022-03-02,164.389999,167.360001,162.949997,166.559998,164.678101,79724800,APPLE Inc
2,2022-03-03,168.470001,168.910004,165.550003,166.229996,164.351837,76678400,APPLE Inc
3,2022-03-04,164.490005,165.550003,162.100006,163.169998,161.326401,83737200,APPLE Inc
4,2022-03-05,163.360001,165.020004,159.039993,159.300003,157.500137,96418800,APPLE Inc
...,...,...,...,...,...,...,...,...
1579,NaT,902.989990,922.250000,892.039978,903.630005,903.630005,45244100,NVIDIA Corp
1580,NaT,884.479980,900.940002,876.200012,894.520020,894.520020,43306400,NVIDIA Corp
1581,NaT,884.840027,903.739990,884.000000,889.640015,889.640015,36845000,NVIDIA Corp
1582,NaT,904.059998,906.340027,858.799988,859.049988,859.049988,43496500,NVIDIA Corp
1583,NaT,867.030029,884.809998,859.260010,880.080017,880.080017,39737044,NVIDIA Corp

In [15]:
df = pd.merge(df_stock, combined_df, on=['Date', 'company_name'], how='left')

df.to_csv('./data.csv', index=False)